coverage:
  status:
    project:
      default:
        target: auto # auto compares coverage to the previous base commit
        # adjust accordingly based on how flaky your tests are
        # this allows a 0% drop from the previous base commit coverage
        threshold: 0%
        only_pulls: true # no status will be posted for commits not on a pull request
    patch:
      default:
        target: auto
        threshold: 0%
        only_pulls: true

github_checks:
  annotations: false

ignore:
  - "core-models"


# When modifying this file, please validate using
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate