name: 'GitHub Version'
description: 'Runs the GitHub version gradle task to publish a new gradle version.'
outputs:
  version:
    description: "The version tag this created."
    value: ${{ steps.get-tag.outputs.tag }}
runs:
  using: "composite"
  steps:
    - id: get-tag
      run: echo "::set-output name=tag::$(./gradlew -q getVersion)"
      shell: bash
    - run: echo Got version ${{ steps.get-tag.outputs.tag }}
      shell: bash
    - run: ./gradlew build bintrayUploadAll -Pbintray.dryRun
      shell: bash
    - run: ./gradlew ciPerformRelease
      shell: bash